name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd ./rust
        cargo build --release
        tree ./target
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: xi-linux-amd64-0.3.0
        path: ./rust/target/release/xi-core
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd ./rust
        cargo build --release
        ls
        tree ./target
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: xi-windows-amd64-0.3.0
        path: ./rust/target/release/xi-core.exe
